#############
# In order to make this run the folders must exist on the synology NAS
#    /volume1/docker/docker-multi/var/lib/mysql
#
#############

services:
  app1:
    build:
      context: app1  
    ports:
      - 3000:3000 
    volumes:
      - ./app1:/app1 
    networks:
      - private
      - public
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos 
  app2:
    build:
      context: app2  
    ports:
      - 3001:3001 
    volumes:
      - ./app2:/app2 
    networks:
      - private
      - public
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos 
  db:
    image: mysql:8.0
    volumes:
      - /volume1/docker/docker-multi/var/lib/mysql:/var/lib/mysql
    networks:
      - private
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

networks:
  public:
  private:
volumes:
  todo-mysql-data: